services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=3000
      - PGID=545
      - UMASK=002
      - TZ=America/Denver
    volumes:
      - /home/serveradmin/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=3000
      - PGID=545
      - UMASK=002
      - TZ=America/Denver
    volumes:
      - /home/serveradmin/radarr/data:/config
      - /media/movies:/movies
      - /media/torrents:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=3000
      - PGID=545
      - UMASK=002
      - TZ=America/Denver
    volumes:
      - /home/serveradmin/sonarr/data:/config
      - /media/tv:/tv
      - /media/torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
